# Generated by Django 6.0.5 on 2026-05-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Национальность')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название стиля')),
                ('description', models.TextField(blank=True, verbose_name='Описание стиля')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Исторический период')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год создания')),
                ('technique', models.CharField(choices=[('oil', 'Масло'), ('watercolor', 'Акварель'), ('tempera', 'Темпера'), ('fresco', 'Фреска'), ('pastel', 'Пастель'), ('acrylic', 'Акрил'), ('gouache', 'Гуашь'), ('other', 'Другое')], default='oil', max_length=20, verbose_name='Техника')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Ширина (см)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Высота (см)')),
                ('museum', models.CharField(blank=True, max_length=200, verbose_name='Музей / Место хранения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, help_text='Вставьте прямую ссылку на изображение картины', verbose_name='Ссылка на изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='gallery.artist', verbose_name='Художник')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='gallery.style', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='gallery.style', verbose_name='Основной стиль'),
        ),
    ]
